style: 1
rate: 50
delay: 1.0
rosbag: true
topics:
 - topic: /one/lora/packets
   fields:
   - field: /serial
   - field: /rssi
   - field: /snr
   - field: /spreading_factor
   - field: /bandwidth
 - topic: /two/lora/packets
   fields:
   - field: /serial
   - field: /rssi
   - field: /snr
   - field: /spreading_factor
   - field: /bandwidth
 - topic: /odom
 - topic: /scan
 - topic: /out/lines 